global:
  scrape_interval: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090','phpmyadmin:8081','localhost:8090','localhost:3306', 'localhost:8000']
